CREATE TABLE users (
   id BIGSERIAL PRIMARY KEY,
   first_name VARCHAR(100),
   last_name VARCHAR(100),

   email VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,

   cpf VARCHAR(14) UNIQUE,
   phone VARCHAR(20),

   enabled BOOLEAN NOT NULL DEFAULT TRUE,
   email_verified BOOLEAN NOT NULL DEFAULT FALSE,

   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);